sonar.projectKey=vrp
sonar.projectName=VRP Project

sonar.host.url=http://localhost:9000
sonar.token=sqp_e4565e3c0e6c748cda34530919b8ce10e469c901

# Sources
sonar.sources=vrp-backend,vrp-solver

# Java (Spring Boot)
sonar.java.binaries=vrp-backend/build/classes/java/main

# sonar.javascript.node.maxspace=512

# Encoding
sonar.sourceEncoding=UTF-8

# Optional exclusions
sonar.exclusions=**/node_modules/**,**/build/**,**/__pycache__/**