sonar.projectKey=vrp
sonar.projectName=VRP Project

sonar.host.url=http://localhost:9000
sonar.token=sqp_5fc4faae5ad3e247c0a0f831e6be2648103ed5a7

# Sources
sonar.sources=vrp-backend,vrp-solver

# Java (Spring Boot)
sonar.java.binaries=vrp-backend/build/classes/java/main

# sonar.javascript.node.maxspace=512

# Encoding
sonar.sourceEncoding=UTF-8

# Optional exclusions
sonar.exclusions=**/node_modules/**,**/build/**,**/__pycache__/**